### PR TITLE
Update & version dependencies

### PR DESCRIPTION
**Pull request by garyb**

### CODE REVIEW

**Comment by Fresheyeball** [comment]
Do --tags come along in PRs? I'm not sure this does the trick.

**Comment by garyb** [comment]
I don't think they do.

**Comment by garyb** [comment]
We need to update the `purescript-yaml` dependencies too by the way, but it looks like the branch in contrib is slightly behind the origin. Can you do the honours? It shouldn't break anything, as the breaking change was removing `Sum` and `Product` monoids.

**Comment by Fresheyeball** [comment]
I'd like to delete my contrib branches frankly. With the progress being made with pursuit and the wiki, I don't think they are needed anymore. I can certainly do the honors and get bower updated.

**Comment by paf31** [comment]
I'm also starting to see `contrib` as more of a burden than a help. Maybe we should encourage people to move things out into their private GitHub namespaces. We can still move things into core as necessary (I have a few candidate libraries of my own, for example, but many more which are not of high enough quality).

**Comment by Fresheyeball** [comment]
@garyb I duplicated the work, and `0.0.6` is up on bower. 

@paf31 I agree, contrib is a burden more than a help (this has changed as purescript matures). What I would prefer is a directory attached to `pursuit` where we can add "recommended" libs by pull request.

**Comment by paf31** [comment]
You can add libraries to Pursuit by PR right now: https://github.com/purescript/pursuit#getting-your-library-included

**Comment by Fresheyeball** [comment]
I know, it rocks. Pursuit rocks, and once it supports duplicates I will be in heaven. But a directory would also be nice.

**Comment by garyb** [comment]
Do you want me to delete the contrib branches for:

- `purescript-oo-ffi`
- `purescript-yaml`
- `purescript-mocha`
- `purescript-chai`
- `purescript-timers`
- `purescript-events`

then? It shouldn't break anything as the bower packages are all registered to you rather than via `purescript-contrib`

**Comment by Fresheyeball** [comment]
yes. go for it.

**Pull request merged**
